// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:715332504776:web:b47ac3b1e30d897ce069fd',
    messagingSenderId: '715332504776',
    projectId: 'platform-954da',
    authDomain: 'platform-954da.firebaseapp.com',
    storageBucket: 'platform-954da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: '1:715332504776:android:2295989846b60d11e069fd',
    messagingSenderId: '715332504776',
    projectId: 'platform-954da',
    storageBucket: 'platform-954da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:715332504776:ios:a66534e53f02806be069fd',
    messagingSenderId: '715332504776',
    projectId: 'platform-954da',
    storageBucket: 'platform-954da.firebasestorage.app',
    iosClientId: '715332504776-0bha0nqlbb9u1fra5f557mqg19i9km72.apps.googleusercontent.com',
    iosBundleId: 'com.example.platform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_MACOS'),
    appId: '1:715332504776:ios:a66534e53f02806be069fd',
    messagingSenderId: '715332504776',
    projectId: 'platform-954da',
    storageBucket: 'platform-954da.firebasestorage.app',
    iosClientId: '715332504776-0bha0nqlbb9u1fra5f557mqg19i9km72.apps.googleusercontent.com',
    iosBundleId: 'com.example.platform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WINDOWS'),
    appId: '1:715332504776:web:ba14c9a5efa9c88fe069fd',
    messagingSenderId: '715332504776',
    projectId: 'platform-954da',
    authDomain: 'platform-954da.firebaseapp.com',
    storageBucket: 'platform-954da.firebasestorage.app',
  );
}
